In [1]:
import tensorflow as tf
from tensorflow import keras

2022-04-19 14:56:32.339655: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/benson516/agv_ws/devel/lib:/opt/ros/noetic/lib
2022-04-19 14:56:32.339675: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


# Strings

In [2]:
tf.constant(b"hello world")

2022-04-19 15:00:50.972325: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2022-04-19 15:00:54.406784: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-04-19 15:00:54.406804: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (benson516-P1G2): /proc/driver/nvidia/version does not exist
2022-04-19 15:00:54.407383: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [5]:
u = tf.constant([ord(c) for c in "cafe"])

In [6]:
u

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 101], dtype=int32)>

In [7]:
b = tf.strings.unicode_encode(u, "UTF-8")

In [8]:
b

<tf.Tensor: shape=(), dtype=string, numpy=b'cafe'>

In [9]:
tf.strings.length(b, unit="UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [10]:
tf.strings.unicode_decode(b,"UTF-8")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 101], dtype=int32)>

Multiple strings

In [15]:
p = tf.constant(["cafe", "coffee", "caffe", "ca fey"])

In [16]:
p

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'cafe', b'coffee', b'caffe', b'ca fey'], dtype=object)>

In [17]:
tf.strings.length(p, unit="UTF8_CHAR")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 6, 5, 6], dtype=int32)>

In [18]:
r = tf.strings.unicode_decode(p, "UTF8")

In [19]:
r

<tf.RaggedTensor [[99, 97, 102, 101], [99, 111, 102, 102, 101, 101], [99, 97, 102, 102, 101], [99, 97, 32, 102, 101, 121]]>

In [20]:
print(r)

<tf.RaggedTensor [[99, 97, 102, 101], [99, 111, 102, 102, 101, 101], [99, 97, 102, 102, 101], [99, 97, 32, 102, 101, 121]]>


# Ragged Tensors

In [21]:
print(r[1])

tf.Tensor([ 99 111 102 102 101 101], shape=(6,), dtype=int32)


In [23]:
r2 = tf.constant([[65, 65], [], [67]])

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [29]:
r2 = tf.ragged.constant([[65, 66], [], [67]])

In [30]:
r2

<tf.RaggedTensor [[65, 66], [], [67]]>

In [31]:
print(tf.concat([r, r2], axis=0))

<tf.RaggedTensor [[99, 97, 102, 101], [99, 111, 102, 102, 101, 101], [99, 97, 102, 102, 101], [99, 97, 32, 102, 101, 121], [65, 66], [], [67]]>


Concatenate along other axis

In [32]:
r3 = tf.ragged.constant([[68, 69, 70], [71], [], [72, 73]])

In [33]:
print(tf.concat([r, r3], axis=1))

<tf.RaggedTensor [[99, 97, 102, 101, 68, 69, 70], [99, 111, 102, 102, 101, 101, 71], [99, 97, 102, 102, 101], [99, 97, 32, 102, 101, 121, 72, 73]]>


In [35]:
r4 = tf.ragged.constant([[68, 69, 70], [71], [72]])

In [36]:
print(tf.concat([r, r4], axis=1))

InvalidArgumentError: Input tensors have incompatible shapes.
Condition x == y did not hold.
First 1 elements of x:
[3]
First 1 elements of y:
[4]

In [37]:
r5 = tf.ragged.constant([[68, 69, 70], [71], [], [72, 73], [74, 75]])

In [38]:
print(tf.concat([r, r5], axis=1))

InvalidArgumentError: Input tensors have incompatible shapes.
Condition x == y did not hold.
First 1 elements of x:
[5]
First 1 elements of y:
[4]

In [39]:
r.to_tensor()

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 99,  97, 102, 101,   0,   0],
       [ 99, 111, 102, 102, 101, 101],
       [ 99,  97, 102, 102, 101,   0],
       [ 99,  97,  32, 102, 101, 121]], dtype=int32)>

In [46]:
r3.to_tensor(default_value=-100)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[  68,   69,   70],
       [  71, -100, -100],
       [-100, -100, -100],
       [  72,   73, -100]], dtype=int32)>

# Sparse Tensors

In [48]:
s = tf.SparseTensor(indices=[[0,1], [1,0], [2,3]],
                    values=[1., 2., 3.],
                    dense_shape=[3, 4])

In [50]:
s

In [51]:
print(s)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [52]:
tf.sparse.to_dense(s)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 3.]], dtype=float32)>

In [53]:
s * 3.14

In [55]:
s + 42.0

TypeError: unsupported operand type(s) for +: 'SparseTensor' and 'float'

# Tensor Arrays

In [66]:
array = tf.TensorArray(dtype=tf.float32, size=3)
array = array.write(0, tf.constant([1., 2.]))
array = array.write(1, tf.constant([3., 10.]))
array = array.write(2, tf.constant([5., 7.]))

In [67]:
array

In [68]:
tensor1 = array.read(1) # => returns (and pops!) tf.constant([3., 10.])

In [69]:
tensor1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3., 10.], dtype=float32)>

In [70]:
array

In [71]:
array.stack()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [0., 0.],
       [5., 7.]], dtype=float32)>

# Sets

In [72]:
a = tf.constant([[1, 5, 9]])
b = tf.constant([[5, 6, 9, 11]])
u = tf.sets.union(a, b)
print(u)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]], shape=(5, 2), dtype=int64), values=tf.Tensor([ 1  5  6  9 11], shape=(5,), dtype=int32), dense_shape=tf.Tensor([1 5], shape=(2,), dtype=int64))


In [74]:
u

In [75]:
tf.sparse.to_dense(u)

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 1,  5,  6,  9, 11]], dtype=int32)>

In [78]:
a = tf.constant([[1, 5, 9], [10, 0, 0]])
b = tf.constant([[5, 6, 9, 11], [13, 0, 0, 0]])
u = tf.sets.union(a,b)
tf.sparse.to_dense(u)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  5,  6,  9, 11],
       [ 0, 10, 13,  0,  0]], dtype=int32)>

In [79]:
tf.sparse.to_dense(u, default_value=-1)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  5,  6,  9, 11],
       [ 0, 10, 13, -1, -1]], dtype=int32)>

# Queues

In [87]:
q = tf.queue.FIFOQueue(3, [tf.int32, tf.string], shapes=[(),()])
q.enqueue([10, b"windy"])
q.enqueue([15, b"sunny"])
q.size()

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [88]:
q.dequeue()

[<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'windy'>]

In [89]:
q.size()

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Enqueue and dequeue multiple records at once

In [90]:
q.enqueue_many([[13, 16], [b'cloudy', b'rainy']])

In [91]:
q.size()

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [92]:
q.dequeue_many(3)

[<tf.Tensor: shape=(3,), dtype=int32, numpy=array([15, 13, 16], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=string, numpy=array([b'sunny', b'cloudy', b'rainy'], dtype=object)>]

In [93]:
q.size()

<tf.Tensor: shape=(), dtype=int32, numpy=0>